services:
  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: frontend-container
    ports:
      - "3000:3000"

  executor:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.executor
    container_name: executor-container
    ports:
      - "8000:8000"
    depends_on:
      - redis

  submission:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.submission
    container_name: submission-container
    ports:
      - "3002:3002"
    depends_on:
      - redis

  ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    container_name: ws-container
    ports:
      - "4000:4000"
    depends_on:
      - redis

