services:
  # web:
  #   build:
  #     context: ./apps/web
  #   ports:
  #     - "3000:3000"
    # depends_on:
    #   - backend

  executor:
    build:
      context: ../apps/executor
    env_file:
     - ../apps/executor/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ../apps/executor
    command: celery -A code.celery_app worker --loglevel=info
    depends_on:
      - redis
      - executor


