FROM node:22-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./packages/db/.env ./packages/db/.env
COPY ./yarn.lock ./yarn.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web
COPY ./apps/web/.env ./apps/web/.env

RUN yarn install
RUN yarn run db:generate
RUN yarn run build

EXPOSE 3000

CMD ["yarn", "run", "start:web"]