FROM python:3.11-alpine

WORKDIR /executor

COPY ./apps/executor/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./apps/executor/ .

EXPOSE 8000

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 & celery -A code.celery_app worker --loglevel=info"]
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]