FROM node:22-alpine

WORKDIR /usr/src/submission-webhook

RUN apk add --no-cache python3 make g++ openssl musl-dev libc6-compat

COPY ./packages ./packages
COPY ./packages/db/.env ./packages/db/.env
COPY ./yarn.lock ./yarn.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/submission-webhook ./apps/submission-webhook

RUN yarn install
RUN rm -rf node_modules/.prisma
RUN yarn run db:generate
RUN yarn run build

EXPOSE 3002

CMD ["yarn", "run", "start:sub"]

